# baseURL = "http://example.org/"
baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "BEL Language"
theme = "learn"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
disableLanguageSwitchingButton = true

[params]
# editURL = "https://github.com/belbio/bel_lang_ws/tree/master/content/"
description = "Documentation for BEL Language"
author = "William Hayes"
showVisitedLinks = false
disableBreadcrumb = false
disableNextPrev = false
themeVariant = "belbio"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation for BEL Language"
weight = 1
languageName = "English"

[[menu.shortcuts]]
name = "<i class='fas fa-home'></i> BEL website"
identifier = "home"
url = "https://bel.bio"
weight = 10

[[menu.shortcuts]]
name = "<i class='far fa-comments'></i> BEL Discussions"
identifier = "forum"
url = "https://forum.bel.bio"
weight = 15

