# baseURL = "http://example.org/"
baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "BEL Language"
theme = "learn"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
disableLanguageSwitchingButton = true

[params]
# editURL = "https://github.com/belbio/bel_lang_ws/tree/master/content/"
description = "Documentation for BEL Language"
author = "William Hayes"
showVisitedLinks = true
disableBreadcrumb = false
disableNextPrev = false
themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation for BEL Language"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> <label>Github repo</label>"
identifier = "ds"
url = "https://github.com/belbio/bel_lang_ws"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> <label>Credits</label>"
url = "/credits"
weight = 30
